apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "examhelm.fullname" . }}
  namespace: {{ .Values.moviedb.namespace }}  
  labels:
    {{- include "examhelm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.moviedb.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "examhelm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "examhelm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{/*  serviceAccountName: {{ include "examhelm.serviceAccountName" . }} 
*/}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext: 
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.moviedb.image }}:{{ .Values.moviedb.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.moviedb.pullPolicy }}
          env:
            - name: {{ .Values.moviedb.env.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretmovie.name }}
                  key: password
          envFrom:
            - configMapRef:  
                name: {{ include "examhelm.fullname" . }}-configmapmovie 
{{/*          ports:
            - name: http-web
              containerPort: {{ .Values.moviedb.service.containerPort }}
              protocol: TCP */}}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
        configMap:
          name: {{- include "examhelm.fullname" . }}-configmapmovie
{{/*          {{- range $key, $value := .Values.castdb.envFrom.configMap }}
          {{- end }} */}}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
