apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretmovie.name }}
{{/*  namespace: standard */}}
  namespace: {{ .Values.moviedb.namespace }}
type: Opaque
data:
  password: {{ .Values.secretmovie.password }}
