apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretcast.name }}
{{/*  namespace: standard */}}
  namespace: {{ .Values.castdb.namespace }}
type: Opaque
data:
  password: {{ .Values.secretcast.password }}
