apiVersion: v1
kind: Service
metadata:
  name: {{ include "examhelm.fullname" . }}-nginx
  namespace: {{ .Values.nginx.namespace }}
  labels:
    {{- include "examhelm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      protocol: TCP
{{/*      name: http  */}}
  selector:
    {{- include "examhelm.selectorLabels" . | nindent 4 }}
