apiVersion: v1
kind: Service
metadata:
  name: {{ include "examhelm.fullname" . }}-cast
  namespace: {{ .Values.cast.namespace }}
  labels:
    {{- include "examhelm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cast.service.type }}
  ports:
    - port: {{ .Values.cast.service.port }}
      targetPort: {{ .Values.cast.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "examhelm.selectorLabels" . | nindent 4 }}
